# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudunits2-dev
r_packages:
  - covr
bioc_packages:
  - Biobase
  - AnnotationDbi
  - impute
  - preprocessCore
  - clusterProfiler
  - GEOquery
  - WGCNA
  - STRINGdb
  - GO.db
git:
  submodules: false
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
